#
#    This file is part of the Pi Entertainment System (PES).
#
#    PES provides an interactive GUI for games console emulators
#    and is designed to work on the Raspberry Pi.
#
#    Copyright (C) 2020-2021 Neil Munday (neil@mundayweb.com)
#
#    PES is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    PES is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with PES.  If not, see <http://www.gnu.org/licenses/>.
#

---
- name: "install packages"
  pacman:
    state: present
    name:
      - alsa-utils
      - autoconf
      - automake
      - bison
      - byacc
      - dhcpcd
      - dosfstools
      - fakeroot
      - flex
      - gcc
      - git
      - gnu-free-fonts
      - cmake
      - crda
      - inetutils
      - iw
      - joyutils
      - kodi-platform
      - kodi-rpi-legacy
      - kodi-rpi-legacy-dev
      - kodi-rpi-legacy-eventclients
      - kodi-rpi-legacy-tools-texturepacker
      - libpulse
      - lsof
      - make
      - man
      - mesa
      - mesa-libgl
      - mc
      - p7zip
      - patch
      - pulseaudio
      - pulseaudio-alsa
      - pkg-config
      - pyqt-builder
      - python-pip
      - python-pyqt5
      - python-qtpy
      - python-sqlalchemy
      - python-dbus
      - python-requests
      - qt5-base
      - qt5-declarative
      - qt5-multimedia
      - qt5-quickcontrols
      - qt5-quickcontrols2
      - rsync
      - scons
      - screen
      - sdl2
      - strace
      - sudo
      - swig
      - ttf-liberation
      - unzip
      - vim
      - wget
      - wpa_supplicant
      - xa
      - zip
