#
#    This file is part of the Pi Entertainment System (PES).
#
#    PES provides an interactive GUI for games console emulators
#    and is designed to work on the Raspberry Pi.
#
#    Copyright (C) 2020-2022 Neil Munday (neil@mundayweb.com)
#
#    PES is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    PES is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with PES.  If not, see <http://www.gnu.org/licenses/>.
#

---
- name: "install dev packages"
  pacman:
    name: "{{ item }}"
    state: present
  with_items: "{{ dev_packages }}"
  when: dev_mode

- name: install common packages
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
      - alsa-utils
      - dhcpcd
      - dosfstools
      - gnu-free-fonts
      - crda
      - inetutils
      - iw
      - joyutils
      - kodi-platform
      - kodi-rpi
      - kodi-rpi-eventclients
      - kodi-rpi-tools-texturepacker
      - libpulse
      - lsof
      - man-db
      - mesa
      - mesa-libgl
      - mc
      - p7zip
      - parted
      - pulseaudio
      - pulseaudio-alsa
      - python-dbus
      - python-flask
      - python-pyqt5
      - python-qtpy
      - python-sqlalchemy
      - python-requests
      - python-waitress
      - qt5-base
      - qt5-declarative
      - qt5-multimedia
      - qt5-quickcontrols
      - qt5-quickcontrols2
      - rsync
      - scons
      - screen
      - sdl2
      - strace
      - sudo
      - swig
      - ttf-liberation
      - unzip
      - vim
      - wget
      - wpa_supplicant
      - xa
      - zip

- name: install PES packages
  pacman:
    name: "{{ item }}"
    state: present
  with_items: "{{ pes_packages }}"
  when: not dev_mode

- name: check Raspberry Pi model
  shell: cat /sys/firmware/devicetree/base/model
  register: model_rslt

- name: install rpi-eeprom for newer Raspberry Pis
  package:
    name: rpi-eeprom
    state: present
  when: "'Raspberry Pi 4 Model B' in model_rslt.stdout"
