#
#    This file is part of the Pi Entertainment System (PES).
#
#    PES provides an interactive GUI for games console emulators
#    and is designed to work on the Raspberry Pi.
#
#    Copyright (C) 2020 Neil Munday (neil@mundayweb.com)
#
#    PES is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    PES is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with PES.  If not, see <http://www.gnu.org/licenses/>.
#

---

- name: "include distcc vars"
  include_vars: "distcc_vars.yml"

- name: "install distcc"
  pacman:
    state: present
    name: distcc

- name: "apply distccd config"
  copy:
    src: distccd
    dest: /etc/conf.d/distccd
    owner: root
    group: root
    mode: 0644

- name: "start distccd"
  service:
    name: distccd
    state: started
    enabled: yes

- name: "set distcc hosts in /etc/makepkg.conf"
  lineinfile:
    path: /etc/makepkg.conf
    regexp: '^DISTCC_HOSTS'
    line: "DISTCC_HOSTS=\"127.0.0.1 {{ distcc_hosts }}\""
  when: distcc_hosts is defined

- name: "enable distcc in /etc/makepkg.conf"
  lineinfile:
    path: /etc/makepkg.conf
    regexp: '^BUILDENV='
    line: "BUILDENV=(distcc color !ccache check !sign)"
  when: distcc_hosts is defined

- name: "disable distcc in /etc/makepkg.conf"
  lineinfile:
    path: /etc/makepkg.conf
    regexp: '^BUILDENV='
    line: "BUILDENV=(!distcc color !ccache check !sign)"
  when: distcc_hosts is undefined
