#
#    This file is part of the Pi Entertainment System (PES).
#
#    PES provides an interactive GUI for games console emulators
#    and is designed to work on the Raspberry Pi.
#
#    Copyright (C) 2020-2023 Neil Munday (neil@mundayweb.com)
#
#    PES is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    PES is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with PES.  If not, see <http://www.gnu.org/licenses/>.
#

---
- name: Add pi group
  ansible.builtin.group:
    name: pi
    state: present

- name: Add sudoers group
  ansible.builtin.group:
    name: sudoers
    state: present

- name: Create /etc/sudoers.d/sudoers
  ansible.builtin.copy:
    src: sudoers
    dest: /etc/sudoers.d/sudoers
    owner: root
    group: root
    mode: "0700"
    validate: /usr/sbin/visudo -csf %s

- name: Add pi user
  ansible.builtin.user:
    name: pi
    comment: pi
    group: pi
    groups: audio,input,video,users,sudoers
    password: $6$GvT7CN63Xj0gDNQl$EuxZ1x/z6HjhK/ttjcsGzscBAnwftbI81CkJ1Y9FJwaCXyNKaiR9zRZ7dhScXTaz8/RytZwQZVUprQdROPGcG0
    create_home: true
    home: /home/pi
    state: present

- name: Create /etc/systemd/system/getty@tty1.service.d
  ansible.builtin.file:
    path: /etc/systemd/system/getty@tty1.service.d
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Enable auto login for pi user
  ansible.builtin.copy:
    src: autologin.conf
    dest: /etc/systemd/system/getty@tty1.service.d/autologin.conf
    owner: root
    group: root
    mode: "0644"

- name: Set-up pi .bash_profile
  ansible.builtin.copy:
    src: bash_profile
    dest: /home/pi/.bash_profile
    owner: pi
    group: pi
    mode: "0600"

- name: Set-up pi .bashrc
  ansible.builtin.copy:
    src: bashrc
    dest: /home/pi/.bashrc
    owner: pi
    group: pi
    mode: "0600"

- name: Remove alarm user
  ansible.builtin.user:
    name: alarm
    state: absent
    force: true

- name: Remove alarm group
  ansible.builtin.group:
    name: alarm
    state: absent
