#
#    This file is part of the Pi Entertainment System (PES).
#
#    PES provides an interactive GUI for games console emulators
#    and is designed to work on the Raspberry Pi.
#
#    Copyright (C) 2020-2022 Neil Munday (neil@mundayweb.com)
#
#    PES is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    PES is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with PES.  If not, see <http://www.gnu.org/licenses/>.
#
---

- name: create Kodi dirs for pi user
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    owner: pi
    group: pi
    mode: 0755
  with_items:
    - /home/pi/.kodi
    - /home/pi/.kodi/userdata
    - /home/pi/.kodi/userdata/peripheral_data
    - /data/pes/kodi
    - /data/pes/kodi/Movies
    - /data/pes/kodi/Music
    - /data/pes/kodi/Pictures
    - /data/pes/kodi/TV

- name: check if ~pi/.kodi/userdata/sources.xml exists
  ansible.builtin.stat:
    path: /home/pi/.kodi/userdata/sources.xml
  register: sources_stat_rslt

- name: create ~pi/.kodi/userdata/sources.xml
  ansible.builtin.copy:
    src: sources.xml
    dest: /home/pi/.kodi/userdata/sources.xml
    owner: pi
    group: pi
    mode: 0644
  when: not sources_stat_rslt.stat.exists

- name: check if ~/pi/.kodi/userdata/peripheral_data/cec_CEC_Adapter.xml exists
  ansible.builtin.stat:
    path: /home/pi/.kodi/userdata/peripheral_data/cec_CEC_Adapter.xml
  register: cec_rslt

- name: create ~/pi/.kodi/userdata/peripheral_data/cec_CEC_Adapter.xml
  ansible.builtin.copy:
    src: cec_CEC_Adapter.xml
    dest: /home/pi/.kodi/userdata/peripheral_data/cec_CEC_Adapter.xml
    owner: pi
    group: pi
    mode: 0644
  when: not cec_rslt.stat.exists
