#
#    This file is part of the Pi Entertainment System (PES).
#
#    PES provides an interactive GUI for games console emulators
#    and is designed to work on the Raspberry Pi.
#
#    Copyright (C) 2020-2023 Neil Munday (neil@mundayweb.com)
#
#    PES is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    PES is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with PES.  If not, see <http://www.gnu.org/licenses/>.
#

---
- name: "gather existing partition information"
  community.general.parted:
    device: /dev/mmcblk0
    unit: MiB
  register: device_info

- name: "create /data mount point"
  ansible.builtin.file:
    path: /data
    state: directory
    mode: "0755"

- name: "create /data FAT32 partition"
  community.general.parted:
    device: /dev/mmcblk0
    fs_type: fat32
    part_end: "100%"
    part_start: "{{ device_info.partitions[-1].end + 1 }}MiB"
    number: 3
    state: present

- name: "format /data"
  community.general.filesystem:
    dev: /dev/mmcblk0p3
    fstype: vfat
    opts: "-n data"
    state: present

- name: "mount /data"
  ansible.posix.mount:
    boot: true
    fstype: vfat
    path: /data
    opts: defaults,uid=pi,gid=pi
    src: /dev/mmcblk0p3
    state: mounted

- name: "create /data/pes"
  ansible.builtin.file:
    state: directory
    path: /data/pes
    mode: "0755"

- name: "create sym link for pi user"
  ansible.builtin.file:
    state: link
    src: /data/pes
    dest: /home/pi/pes
