#
#    This file is part of the Pi Entertainment System (PES).
#
#    PES provides an interactive GUI for games console emulators
#    and is designed to work on the Raspberry Pi.
#
#    Copyright (C) 2020-2023 Neil Munday (neil@mundayweb.com)
#
#    PES is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    PES is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with PES.  If not, see <http://www.gnu.org/licenses/>.
#

---
- name: Set hostname
  ansible.builtin.hostname:
    name: pes

- name: Apply /boot/config.txt settings
  ansible.builtin.template:
    src: config.txt.j2
    dest: /boot/config.txt
    owner: root
    group: root
    mode: "0755"

- name: Apply /boot/cmdline.txt settings
  ansible.builtin.copy:
    src: cmdline.txt
    dest: /boot/cmdline.txt
    owner: root
    group: root
    mode: "0755"

- name: Set timezone to Europe/London
  community.general.timezone:
    name: Europe/London

- name: Set keyboard layout to UK
  ansible.builtin.command:
    cmd: localectl set-keymap --no-convert uk
  register: localectl_output
  changed_when: localectl_output.rc != 0

- name: Disable core files
  ansible.builtin.lineinfile:
    path: /etc/systemd/system.conf
    regexp: ^DumpCore=
    insertafter: ^#DumpCore=
    line: DumpCore=no

- name: Limit journal file to 50MB
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    regexp: ^SystemMaxUse=
    insertafter: ^#SystemMaxUse=
    line: SystemMaxUse=50M

- name: Disable DNSSEC - we don't have a RTC
  ansible.builtin.lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: ^DNSSEC=
    insertafter: ^#DNSSEC=
    line: DNSSEC=no

- name: Enable dhcpcd
  ansible.builtin.service:
    name: dhcpcd
    state: started
    enabled: true

- name: Add udev rules for USB control pads
  ansible.builtin.copy:
    src: 99-evdev.rules
    dest: /etc/udev/rules.d/99-evdev.rules
    owner: root
    group: root
    mode: "0644"

- name: Set-up root .bash_profile
  ansible.builtin.copy:
    src: bash_profile
    dest: /root/.bash_profile
    owner: root
    group: root
    mode: "0600"

- name: Set-up root .bashrc
  ansible.builtin.copy:
    src: bashrc
    dest: /root/.bashrc
    owner: root
    group: root
    mode: "0600"

- name: Set-up makepkg.conf
  ansible.builtin.lineinfile:
    path: /etc/makepkg.conf
    regexp: ^MAKEFLAGS=
    insertafter: ^#MAKEFLAGS=
    line: MAKEFLAGS="-j {{ ansible_processor_vcpus }}"
