#
#    This file is part of the Pi Entertainment System (PES).
#
#    PES provides an interactive GUI for games console emulators
#    and is designed to work on the Raspberry Pi.
#
#    Copyright (C) 2020 Neil Munday (neil@mundayweb.com)
#
#    PES is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    PES is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with PES.  If not, see <http://www.gnu.org/licenses/>.
#

---

- name: "install bluetooth packages"
  pacman:
    state: present
    name:
      - bluez
      - bluez-utils

- name: "auto enable Bluetooth"
  lineinfile:
    path: /etc/bluetooth/main.conf
    regexp: '^AutoEnable='
    insertafter: '^#AutoEnable='
    line: AutoEnable=true

- name: "disable discoverable timeout"
  lineinfile:
    path: /etc/bluetooth/main.conf
    regexp: '^DiscoverableTimeout='
    insertafter: '^#DiscoverableTimeout='
    line: DiscoverableTimeout=0

- name: "add Bluetooth dtoverlay to /boot/config.txt"
  lineinfile:
    path: /boot/config.txt
    regexp: '^dtoverlay='
    insertbefore: '^gpu_mem='
    line: dtoverlay=bcmbt

- name: "create systemd-udevd.service.d"
  file:
    state: directory
    dest: /etc/systemd/system/systemd-udevd.service.d
    owner: root
    group: root
    mode: 0755

- name: "create systemd-udevd.service.d/override.conf"
  copy:
    src: systemd-udevd.service.d/override.conf
    dest: /etc/systemd/system/systemd-udevd.service.d/override.conf
    owner: root
    group: root
    mode: 0644
  register: override_result

- name: "reload systemd"
  command: systemctl daemon-reload
  when: override_result.changed

- name: create /opt/sbin
  file:
    path: /opt/sbin
    state: directory
    mode: 0700

- name: "install start-bt.sh"
  copy:
    src: start-bt.sh
    dest: /opt/sbin/start-bt.sh
    owner: root
    group: root
    mode: 0700

- name: "create start-bt udev rule"
  copy:
    src: 10-local.rules
    dest: /etc/udev/rules.d/10-local.rules
    owner: root
    group: root
    mode: 0644

- name: "disable bluetooth"
  service:
    name: bluetooth
    state: stopped
    enabled: no
