#
# ~/.bashrc
#

# Ansible managed

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias ll='ls -l'

if [ $TERM != "xterm" ]; then
  setterm -blank 0
fi

if [ ! -n "$SSH_CONNECTION" ] && [ ! -n "$DESKTOP_SESSION" ]; then
  if ! mount | grep -q '/data' || [ ! -d ~/.kodi ]; then
    sudo /opt/pes/set-up/bin/pes-postboot
  fi
  /opt/pes/bin/pes
fi
