#
#    This file is part of the Pi Entertainment System (PES).
#
#    PES provides an interactive GUI for games console emulators
#    and is designed to work on the Raspberry Pi.
#
#    Copyright (C) 2020-2022 Neil Munday (neil@mundayweb.com)
#
#    PES is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    PES is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with PES.  If not, see <http://www.gnu.org/licenses/>.
#

---

- name: "disable systemd-resolved"
  service:
    name: systemd-resolved
    enabled: no
    state: stopped

- name: "check status of /etc/resolv.conf"
  stat:
    path: /etc/resolv.conf
    follow: no
  register: resolv_result

- name: "remove /etc/resolv.conf sym link"
  file:
    state: absent
    path: /etc/resolv.conf
  when: resolv_result.stat.exists and resolv_result.stat.islnk

- name: "get resolvconf output"
  command: "resolvconf -l"
  register: resolvconf_result
  when: not resolv_result.stat.exists or (resolv_result.stat.exists and resolv_result.stat.islnk)

- name: "create /etc/resolv.conf"
  copy:
    dest: /etc/resolv.conf
    content: "{{ resolvconf_result.stdout}}\n"
    owner: root
    group: root
    mode: 0644
  when: not resolv_result.stat.exists or (resolv_result.stat.exists and resolv_result.stat.islnk)
