name: Ansible Lint
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install collections
        run: ansible-galaxy collection install -p /usr/share/ansible/collections -f community.general
      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@main
        env:
          ANSIBLE_LIBRARY: '/usr/share/ansible/collections'
