name: Ansible Lint
on:
  push:
    paths:
      - 'ansible/roles/**.yml'
  pull_request:
    paths:
      - 'ansible/roles/**.yml'
  workflow_dispatch:
    paths:
      - 'ansible/roles/**.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: install ansible-lint
        run: pip install "ansible-lint"
      - name: install community.general
        run: ansible-galaxy collection install -f community.general
      - name: install ansible.posix
        run: ansible-galaxy collection install -f ansible.posix
      - name: lint files
        run: ansible-lint ansible/roles/*
